services:
  memos:
    container_name: memos
    image: neosmemo/memos:stable
    restart: always
    volumes:
      - ~/.memos/:/var/opt/memos
    ports:
      - 5230:5230

volumes:
  memos_data:
    name: memos_data

networks:
  default:
    name: portainer_network
