services:
  minio:
    container_name: minio
    image: quay.io/minio/minio:RELEASE.2025-03-12T18-04-18Z
    restart: always
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001

volumes:
  minio_data:
    name: minio_data

networks:
  default:
    name: portainer_network
