services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

volumes:
  mongo_data:
    name: mongo_data

networks:
  default:
    name: portainer_network
